<html lang="eng">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>makers' lab</title>

    <!-- CSS  -->
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css" rel="stylesheet">
    <link href="../css/style.min.css" rel="stylesheet">

  <script src="https://rawgit.com/emlyon/makerstime/master/AutoPlayifVisible/jquery.min.js"></script>
  <script src="https://rawgit.com/emlyon/makerstime/master/AutoPlayifVisible/lib/bootstrap/bootstrap.min.js"></script>
  <script src="https://rawgit.com/emlyon/makerstime/master/AutoPlayifVisible/lib/vissense.min.js"></script>
  <script src="https://rawgit.com/emlyon/makerstime/master/AutoPlayifVisible/app/app.js"></script>

</head>

<body>

<font size="4">

<div class="container">

  <h3>How to Make the Drone Arm :</h3>

<br>

<!-- <br>

<script src="https://embed.github.com/view/3d/emlyon/makerstime/master/STL/Drone_Arm.stl?height=600&width=1070"></script>

<br><br><br> -->

<h5> Go on the website <a href="https://www.tinkercad.com/">Tinkercad.com</a> </h5>
  <br /> Sign in with your account then select "Create new design" on the Dashboard </p>

<img src="Tuto01_EngMP4/Tinkercad_Eng.png" width="1070" height="790,92">

<br><br><br><br>


<h4>Step 1: Create a cylinder </h4>
<br>

<p> Drag and drop the orange cylinder from the right side panel onto the workplane. </p>
<br>
<video  width="auto" height="600" loop autoplay muted id="video">
  <source src="Tuto01_EngMP4/01.mp4" type="video/mp4">
</video>

<br>
<p> Use the white squares to change the cylinder diameter size to 10.00 mm (10.00 mm width and 10.00 mm depth).
  <br /> The cylinder height does not need to be changed.</p>

<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/02.mp4" type="video/mp4">
</video>
<br>

<p> Now change the setting of the grid by clicking on the box located at the bottom right of the window :
  <br /> Next to "Snap grid 1.0 mm", select 0.25 mm.</p>

<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/03.mp4" type="video/mp4">
</video>
<br>

<p> Then, select the grey (hollow) cylinder in the right panel.
  <br /> Also, again using the white squares, it is necessary to change the cylinder diameter to 7.50 mm width and 7.50 mm depth.</p>

<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/04.mp4" type="video/mp4">
</video>
<br>

<p>Using the black arrow at the top, move the cylinder 2.00 mm up.</p>

<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/05.mp4" type="video/mp4">
</video>

<br><br><br><br><br>

<h4>Étape 2 : Extruder le cylindre orange </h4>
<br>

<p> Holding the left mouse button, select both cylinders.
  <br / > They should both appear with a cyan line.
    <br /> Press the "Align" button (or the L key).
      <br /> A selection grid appears on the rectangle at the level of the workplan, click on the circles located in the middle of the segments of the rectangle.
          <br /> The hollow cylinder is now in the middle of the orange cylinder.</p>

<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/06.mp4" type="video/mp4">
</video>
<br>

<p> Then select the "Group" icon at the top right (or the Ctrl + G key).</p>

<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/07.mp4" type="video/mp4">
</video>
<br>

<p> The orange cylinder is now hollow.</p>

<br><br><br>

<h4>Step 3: Add some vents</h4>
<br>

<p> Therefore, take the hollow cylinder of the side panel.
  <br /> Thanks to the double curved arrows, rotate it to 90°.</p>

<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/08.mp4" type="video/mp4">
</video>
<br>

<p> Then, you need to give it a height of 7.00 mm, a width of 6.00 mm and a depth of 20.00 mm.
  <br /> With the black arrow, move it 1.00 mm up.</p>


<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/09.mp4" type="video/mp4">
</video>
<br>

<p>With the "align" tool, place the hollow cylinder in the center of the orange cylinder.</p>


<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/10.mp4" type="video/mp4">
</video>
<br>

<p> Duplicate the hollow cylinder with the button at the top left (or the Ctrl + D key) and with the black arrow, move it 10.00 mm up.</p>

<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/11.mp4" type="video/mp4">
</video>
<br>

<p> Select the three cylinders and click on "Group" again.</p>

<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/12.mp4" type="video/mp4">
</video>
<br>

<p> The orange cylinder is now pierced by four ovals.</p>

<br><br><br><br><br>

<h4>Step 4: Make the drone arm</h4>
<br>

<p> Select the red box in the right side panel.</p>
<p> After having placed it on the workplane, it must be given a width of 6.50 mm, a height of 6.50 mm and a depth of 20.00 mm.</p>

<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/13.mp4" type="video/mp4">
</video>
<br>

<p> Take a grey cube, it is necessary to give it the following dimensions:
  <br /> 3.25 mm width, 3.25 mm height and 10.00 mm depth.</p>

<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/14.mp4" type="video/mp4">
</video>
<br>

<p> Insert the hollow rectangle in the red rectangle by selecting the two rectangles
  <br /> With the "align" tool, center the hollow rectangle at the edge of the red rectangle using the black handles.</p>

<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/15.mp4" type="video/mp4">
</video>
<br>

<p> Move the red rectangle 1.00 mm backward without moving it laterally. Group the two rectangles together.
  <br /> (ProTip: Pressing the ⇧ SHIFT key after clicking with the mouse locks the movement in one direction )</p>

<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/16.mp4" type="video/mp4">
</video>
<br>

<p> Now, click on the shape "wedge" and put it on the workplane, then perform on this form a 90° rotation on its vertical axis.</p>

<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/17.mp4" type="video/mp4">
</video>
<br>

<p> Give the wedge a height of 13.50 mm and a width of 6.50 mm.</p>

<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/18.mp4" type="video/mp4">
</video>
<br>

<p> Merge with the tool "align" the rectangle and the wedge.</p>

<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/19.mp4" type="video/mp4">
</video>
<br>

<p> Move the 13.50 mm rectangle up in order to place it on the bevel and group the two pieces together.</p>

<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/20.mp4" type="video/mp4">
</video>
<br>

<p> Align this new piece with the previously extruded cylinder.</p>

<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/21.mp4" type="video/mp4">
</video>
<br>

<p> Move the 8.25 mm piece to the right and merge the set.
  <br /> (During assembly, if the motor does not fit, repeat this step and try the value of 8.5 mm )</p>

<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/22.mp4" type="video/mp4">
</video>
<br>

<p> Congratulation !
    <br /> Now you are ready to 3D Print your part !
    <br /> Select "Export" then STL</p>

<video  width="auto" height="600" loop autoplay muted  id="video">
  <source src="Tuto01_EngMP4/23.mp4" type="video/mp4">
</video>

<br>
<p> Tip : Choose 3D Printers with different filament color to differenciate the rear and the front.

Optimal 3D Printing settings : <br>
No support <br>
0.19mm Layer thickness <br>
Quality "Normal" and medium infill. </p>

<br><br>

<!-- <a href="(https://youtu.be/FzPWmxMxMAc?list=PL_t1-MryummxwZb7xBvnf4TLlFhXNdn7D)">Intro to 3D printing</a>

    <br><br><br><br><br><br><br><br> -->

</font>

</body>

</html>
